version: '3.7'

services:
  web:
    image: nginx:alpine
    restart: always
    labels:
      - "traefik.backend=${podName}-web"
      - "traefik.frontend.rule=Host:${hostRule}"
      - "traefik.docker.network=${podName}_frontend"
      - "traefik.port=80"

    networks:
      - frontend
      - backend
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
    command: [nginx, '-g', 'daemon off;']

  php:
    build: .
    restart: always
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    volumes:
      - ./msmtp/msmtprc:/etc/msmtprc
      - ./html:/usr/share/nginx/html:ro

  mariadb:
    image: mariadb
    restart: always
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_DATABASE: ${dbName}
      MYSQL_USER: ${dbUser}
      MYSQL_PASSWORD: ${dbPass}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./database:/var/lib/mysql

  backup:
    image: zeenlym/mariadb-backup
    depends_on:
      - mariadb
    restart: always
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    environment:
      - TIMEZONE=${timeZone}
      - SCHEDULE=0 0 3 * *
      - BACKUP_METHOD=mysqldump
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${dbName}
      - MYSQL_USER=${dbUser}
      - MYSQL_PASSWORD=${dbPass}
    volumes:
      - ./backup:/backup

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    labels:
      - "traefik.backend=${podName}-adminer"
      - "traefik.frontend.rule=Host:${adminerHostRule}"
      - "traefik.docker.network=${podName}_frontend"
      - "traefik.port=8080"

networks:
  frontend:
  backend:
